// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

package com.mycompany.db_emulador;
import java_cup.runtime.*;



@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\1\2\2\1\22\0\1\1\1\0\1\3"+
    "\5\0\1\4\1\5\2\0\1\6\1\0\1\7\1\0"+
    "\12\10\1\0\1\11\1\12\1\13\1\14\2\0\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\16\1\24"+
    "\2\16\1\25\1\26\1\27\1\30\2\16\1\31\1\32"+
    "\1\33\1\34\1\35\3\16\1\36\6\0\2\16\1\37"+
    "\1\40\1\41\1\16\1\42\1\16\1\43\3\16\1\44"+
    "\1\45\1\46\2\16\1\47\1\50\1\51\1\52\1\53"+
    "\1\16\1\54\2\16\12\0\1\2\32\0\1\55\u01df\0"+
    "\1\55\177\0\13\55\35\0\2\2\5\0\1\55\57\0"+
    "\1\55\240\0\1\55\377\0\u0100\56";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\3\11\13\12\1\0\1\13\4\12\1\14"+
    "\2\12\1\15\2\12\1\0\2\12\1\0\7\12\1\16"+
    "\2\12\1\0\11\12\1\0\11\12\1\0\10\12\1\17"+
    "\1\0\1\12\1\20\1\12\1\21\2\12\1\22\1\12"+
    "\1\17\1\12\1\23\1\24\5\12\1\25\2\12\1\26"+
    "\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\57\0\57\0\57\0\57"+
    "\0\215\0\57\0\274\0\57\0\353\0\u011a\0\u0149\0\u0178"+
    "\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0"+
    "\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0149\0\u0439"+
    "\0\u0468\0\u0149\0\u0497\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\57"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb"+
    "\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0149"+
    "\0\u0cab\0\u0cda\0\u0149\0\u0d09\0\u0149\0\u0d38\0\u0d67\0\u0149"+
    "\0\u0d96\0\57\0\u0dc5\0\u0149\0\u0149\0\u0df4\0\u0e23\0\u0e52"+
    "\0\u0e81\0\u0eb0\0\u0149\0\u0edf\0\u0f0e\0\u0149\0\u0149";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\3\17\1\20"+
    "\1\21\1\17\1\22\3\17\1\23\1\17\1\24\2\17"+
    "\1\25\1\17\1\26\3\17\1\27\1\17\1\30\7\17"+
    "\1\2\130\0\1\31\16\0\1\11\4\0\40\32\15\0"+
    "\2\14\55\0\1\14\53\0\1\17\4\0\2\17\1\33"+
    "\7\17\1\34\2\17\1\35\22\17\12\0\1\17\4\0"+
    "\40\17\12\0\1\17\4\0\10\17\1\36\1\17\1\37"+
    "\25\17\12\0\1\17\4\0\7\17\1\40\30\17\12\0"+
    "\1\17\4\0\12\17\1\41\25\17\12\0\1\17\4\0"+
    "\14\17\1\42\23\17\12\0\1\17\4\0\4\17\1\43"+
    "\33\17\12\0\1\17\4\0\1\44\37\17\3\0\2\45"+
    "\5\0\1\17\4\0\40\17\1\45\11\0\1\17\4\0"+
    "\23\17\1\46\14\17\12\0\1\17\4\0\35\17\1\47"+
    "\2\17\53\0\1\50\15\0\1\32\4\0\40\32\12\0"+
    "\1\17\4\0\16\17\1\51\21\17\12\0\1\17\4\0"+
    "\3\17\1\42\34\17\12\0\1\17\4\0\7\17\1\52"+
    "\30\17\12\0\1\17\4\0\7\17\1\53\30\17\12\0"+
    "\1\17\4\0\10\17\1\54\27\17\12\0\1\17\4\0"+
    "\15\17\1\55\22\17\12\0\1\17\4\0\10\17\1\56"+
    "\27\17\12\0\1\17\4\0\10\17\1\57\27\17\55\0"+
    "\1\60\13\0\1\17\4\0\23\17\1\61\14\17\12\0"+
    "\1\17\4\0\27\17\1\62\10\17\51\0\1\63\17\0"+
    "\1\17\4\0\17\17\1\64\20\17\12\0\1\17\4\0"+
    "\6\17\1\65\31\17\12\0\1\17\4\0\11\17\1\66"+
    "\26\17\12\0\1\17\4\0\16\17\1\67\21\17\12\0"+
    "\1\17\4\0\4\17\1\70\33\17\12\0\1\17\4\0"+
    "\4\17\1\71\33\17\12\0\1\17\4\0\13\17\1\72"+
    "\24\17\12\0\1\17\4\0\31\17\1\73\6\17\12\0"+
    "\1\17\4\0\24\17\1\74\13\17\45\0\1\75\23\0"+
    "\1\17\4\0\1\76\37\17\12\0\1\17\4\0\12\17"+
    "\1\77\25\17\12\0\1\17\4\0\7\17\1\100\30\17"+
    "\12\0\1\17\4\0\14\17\1\101\23\17\12\0\1\17"+
    "\4\0\14\17\1\102\23\17\12\0\1\17\4\0\2\17"+
    "\1\103\35\17\12\0\1\17\4\0\14\17\1\104\23\17"+
    "\12\0\1\17\4\0\34\17\1\105\3\17\12\0\1\17"+
    "\4\0\32\17\1\106\5\17\47\0\1\107\21\0\1\17"+
    "\4\0\10\17\1\110\27\17\12\0\1\17\4\0\1\111"+
    "\37\17\12\0\1\17\4\0\12\17\1\112\25\17\12\0"+
    "\1\17\4\0\1\113\37\17\12\0\1\17\4\0\16\17"+
    "\1\114\21\17\12\0\1\17\4\0\2\17\1\115\35\17"+
    "\12\0\1\17\4\0\4\17\1\116\33\17\12\0\1\17"+
    "\4\0\24\17\1\117\13\17\12\0\1\17\4\0\31\17"+
    "\1\120\6\17\44\0\1\121\24\0\1\17\4\0\7\17"+
    "\1\122\30\17\12\0\1\17\4\0\14\17\1\123\23\17"+
    "\12\0\1\17\4\0\1\124\37\17\12\0\1\17\4\0"+
    "\14\17\1\125\23\17\12\0\1\17\4\0\1\126\37\17"+
    "\12\0\1\17\4\0\7\17\1\127\30\17\12\0\1\17"+
    "\4\0\15\17\1\130\22\17\12\0\1\17\4\0\37\17"+
    "\1\131\5\0\1\132\63\0\1\17\4\0\21\17\1\133"+
    "\16\17\12\0\1\17\4\0\14\17\1\134\23\17\12\0"+
    "\1\17\4\0\14\17\1\135\23\17\12\0\1\17\4\0"+
    "\13\17\1\136\24\17\12\0\1\17\4\0\34\17\1\137"+
    "\3\17\12\0\1\17\4\0\1\140\37\17\12\0\1\17"+
    "\4\0\12\17\1\141\25\17\12\0\1\17\4\0\22\17"+
    "\1\142\15\17\12\0\1\17\4\0\14\17\1\143\23\17"+
    "\12\0\1\17\4\0\1\144\37\17\12\0\1\17\4\0"+
    "\33\17\1\145\4\17\12\0\1\17\4\0\14\17\1\146"+
    "\23\17\12\0\1\17\4\0\36\17\1\147\1\17\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[3901];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\4\11\1\1\1\11\1\1\1\11"+
    "\14\1\1\0\13\1\1\0\2\1\1\0\7\1\1\11"+
    "\2\1\1\0\11\1\1\0\11\1\1\0\11\1\1\0"+
    "\10\1\1\11\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("No se reconocio este simbolo: " + yytext());
            }
          // fall through
          case 24: break;
          case 2:
            { /* no hace nada */
            }
          // fall through
          case 25: break;
          case 3:
            { return new Symbol(sym.PARA, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 26: break;
          case 4:
            { return new Symbol(sym.PARC, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 27: break;
          case 5:
            { return new Symbol(sym.COMA, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 28: break;
          case 6:
            { return new Symbol(sym.DOT, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 29: break;
          case 7:
            { return new Symbol(sym.NUMERO, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 30: break;
          case 8:
            { return new Symbol(sym.FINL, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 31: break;
          case 9:
            { return new Symbol(sym.RELAC, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 32: break;
          case 10:
            { return new Symbol(sym.ID, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 33: break;
          case 11:
            { return new Symbol(sym.STRING, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 34: break;
          case 12:
            { return new Symbol(sym.EN, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 35: break;
          case 13:
            { return new Symbol(sym.LOGIC, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 36: break;
          case 14:
            { return new Symbol(sym.CSV, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 37: break;
          case 15:
            { return new Symbol(sym.VALOR, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 38: break;
          case 16:
            { return new Symbol(sym.ASIGNAR, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 39: break;
          case 17:
            { return new Symbol(sym.FILT, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 40: break;
          case 18:
            { return new Symbol(sym.VALORES, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 41: break;
          case 19:
            { return new Symbol(sym.ELIMINAR, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 42: break;
          case 20:
            { return new Symbol(sym.INSERTAR, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 43: break;
          case 21:
            { return new Symbol(sym.ACTUALIZAR, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 44: break;
          case 22:
            { return new Symbol(sym.SELEC, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 45: break;
          case 23:
            { return new Symbol(sym.PATH, yyline+1, yycolumn+1, new String(yytext()));
            }
          // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
