
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.db_emulador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INSERTAR = 4;
  public static final int ELIMINAR = 5;
  public static final int ERROR = 23;
  public static final int LOGIC = 19;
  public static final int PARC = 17;
  public static final int PARA = 16;
  public static final int ID = 10;
  public static final int VALORES = 9;
  public static final int CSV = 13;
  public static final int ASIGNAR = 7;
  public static final int STRING = 21;
  public static final int ACTUALIZAR = 6;
  public static final int COMA = 12;
  public static final int EOF = 0;
  public static final int SELEC = 2;
  public static final int RELAC = 20;
  public static final int NUMERO = 22;
  public static final int error = 1;
  public static final int DOT = 11;
  public static final int FINL = 18;
  public static final int EN = 8;
  public static final int FILT = 3;
  public static final int PATH = 14;
  public static final int VALOR = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELEC",
  "FILT",
  "INSERTAR",
  "ELIMINAR",
  "ACTUALIZAR",
  "ASIGNAR",
  "EN",
  "VALORES",
  "ID",
  "DOT",
  "COMA",
  "CSV",
  "PATH",
  "VALOR",
  "PARA",
  "PARC",
  "FINL",
  "LOGIC",
  "RELAC",
  "STRING",
  "NUMERO",
  "ERROR"
  };
}

